### ISSUE TITLE
Python error calculating isochrone

### ISSUE THREAD

**Issue by JesusLopTem** [riccardoklinger/Hqgis#14]
I get this error when trying to calculate isochrones:
```
ValueError: invalid literal for int() with base 10: '' 
Traceback (most recent call last):
  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HEREqgis/hereqgis.py", line 766, in getIsochronesSingle
    ranges = [int(x) for x in intervalArray]
  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HEREqgis/hereqgis.py", line 766, in 
    ranges = [int(x) for x in intervalArray]
ValueError: invalid literal for int() with base 10: ''


Versión de Python: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Versión de QGIS: 3.2.0-Bonn Bonn, exported 
```

**Comment by JesusLopTem** [comment]
Yes I use same string: 180,360,720. Now when click to get coordinates I get this error:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 591: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HEREqgis/GetMapCoordinates.py", line 79, in clicked
    print(r.text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 591: ordinal not in range(128)
Versión de Python: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Versión de QGIS: 3.2.0-Bonn Bonn, exported 
```

**Comment by riccardoklinger** [comment]
Please share the searched/shown address in the geocode field in a new issue... It is most likely an issues with special characters

**Comment by riccardoklinger** [comment]
Just tried it with special characters and still wokred. Yet I have removed the print statement in the above mentioned coding block.
