### ISSUE TITLE
Error running multiple isochrones at 600, 1200, 1800, 3600 seconds

### ISSUE THREAD

**Issue by golfecholima** [riccardoklinger/Hqgis#71]
```
2021-11-12T14:59:56     WARNING    warning:/Users/work/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Hqgis/hqgis.py:1356: ResourceWarning: unclosed 
              result = self.dlg.exec_()
             
             traceback: File "/Users/work/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Hqgis/hqgis.py", line 1356, in run
              result = self.dlg.exec_()
```
Not sure I understand how to troubleshoot this traceback.

The job is on 8699 points with the following settings.

<img width="531" alt="Screen Shot 2021-11-12 at 3 23 17 PM" src="https://user-images.githubusercontent.com/5105827/141594679-a3f46dd1-31d0-4933-a8fa-31d15a177d58.png">

**Comment by golfecholima** [comment]
Woops, full traceback here:

```
021-11-12T00:08:02     WARNING    Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
              cnx.do_handshake()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
              self._raise_ssl_error(self._ssl, result)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
              raise SysCallError(errno, errorcode.get(errno))
             OpenSSL.SSL.SysCallError: (60, 'ETIMEDOUT')
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
              httplib_response = self._make_request(conn, method, url,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
              self._validate_conn(conn)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
              conn.connect()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect
              self.sock = ssl_wrap_socket(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
              return context.wrap_socket(sock, server_hostname=server_hostname)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 462, in wrap_socket
              raise ssl.SSLError('bad handshake: %r' % e)
             ssl.SSLError: ("bad handshake: SysCallError(60, 'ETIMEDOUT')",)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
              resp = conn.urlopen(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
              retries = retries.increment(method, url, error=e, _pool=self,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='isoline.route.ls.hereapi.com', port=443): Max retries exceeded with url: /routing/7.2/calculateisoline.json?apiKey=Sa6CRUZnkEYpo--IfVr5t5UZCo43rZzfMklnIrCVdMQ&range=600,1200,1800&mode=fastest;car;traffic:enabled&rangetype=time&start=geo!34.154536,-118.471673&departure=2021-09-11T15:00:00Z (Caused by SSLError(SSLError("bad handshake: SysCallError(60, 'ETIMEDOUT')")))
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/work/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Hqgis/hqgis.py", line 1304, in getIsochronesBatch
              r = requests.get(url)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 76, in get
              return request('get', url, params=params, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 61, in request
              return session.request(method=method, url=url, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
              resp = self.send(prep, **send_kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
              r = adapter.send(request, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
              raise SSLError(e, request=request)
             requests.exceptions.SSLError: HTTPSConnectionPool(host='isoline.route.ls.hereapi.com', port=443): Max retries exceeded with url: /routing/7.2/calculateisoline.json?apiKey=Sa6CRUZnkEYpo--IfVr5t5UZCo43rZzfMklnIrCVdMQ&range=600,1200,1800&mode=fastest;car;traffic:enabled&rangetype=time&start=geo!34.154536,-118.471673&departure=2021-09-11T15:00:00Z (Caused by SSLError(SSLError("bad handshake: SysCallError(60, 'ETIMEDOUT')")))
             
2021-11-12T14:59:56     WARNING    Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 456, in wrap_socket
              cnx.do_handshake()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
              self._raise_ssl_error(self._ssl, result)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
              raise SysCallError(errno, errorcode.get(errno))
             OpenSSL.SSL.SysCallError: (60, 'ETIMEDOUT')
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
              httplib_response = self._make_request(conn, method, url,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
              self._validate_conn(conn)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
              conn.connect()
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect
              self.sock = ssl_wrap_socket(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
              return context.wrap_socket(sock, server_hostname=server_hostname)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 462, in wrap_socket
              raise ssl.SSLError('bad handshake: %r' % e)
             ssl.SSLError: ("bad handshake: SysCallError(60, 'ETIMEDOUT')",)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
              resp = conn.urlopen(
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
              retries = retries.increment(method, url, error=e, _pool=self,
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='isoline.route.ls.hereapi.com', port=443): Max retries exceeded with url: /routing/7.2/calculateisoline.json?apiKey=Sa6CRUZnkEYpo--IfVr5t5UZCo43rZzfMklnIrCVdMQ&range=600,1200,1800,3600&mode=fastest;car;traffic:enabled&rangetype=time&destination=geo!34.218642,-119.177799&departure=2021-09-10T15:00:00Z (Caused by SSLError(SSLError("bad handshake: SysCallError(60, 'ETIMEDOUT')")))
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/work/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Hqgis/hqgis.py", line 1304, in getIsochronesBatch
              r = requests.get(url)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 76, in get
              return request('get', url, params=params, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/api.py", line 61, in request
              return session.request(method=method, url=url, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
              resp = self.send(prep, **send_kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
              r = adapter.send(request, **kwargs)
              File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
              raise SSLError(e, request=request)
             requests.exceptions.SSLError: HTTPSConnectionPool(host='isoline.route.ls.hereapi.com', port=443): Max retries exceeded with url: /routing/7.2/calculateisoline.json?apiKey=Sa6CRUZnkEYpo--IfVr5t5UZCo43rZzfMklnIrCVdMQ&range=600,1200,1800,3600&mode=fastest;car;traffic:enabled&rangetype=time&destination=geo!34.218642,-119.177799&departure=2021-09-10T15:00:00Z (Caused by SSLError(SSLError("bad handshake: SysCallError(60, 'ETIMEDOUT')")))
```

**Comment by riccardoklinger** [comment]
can you check with the new version 1.2.0 please? It is available via the plugin manager.
